app/Console/Command/NagvisMigrationShell.php, app/Plugin/MapModule/View/Mapeditors/edit.ctp
[+]added fallback icon also in the edit mode ITC-173
=> [-]Fixed ITC-176 #dev-to-qa-queue

app/Console/Command/NagvisMigrationShell.php, app/Plugin/MapModule/View/Mapeditors/view.ctp
[-]added console output in nagvis migration shell
=> [+]added map name in mapeditors view

app/Plugin/MapModule/Model/Mapeditor.php, app/Plugin/MapModule/webroot/js/app/controllers/mapeditors/edit_controller.js, app/Plugin/MapModule/webroot/js/app/controllers/mapeditors/view_controller.js
[+]gadgets are forced to be a Service
ITC-216 #dev-to-qa-queue
=> [+]empty map objects will be deleted again

app/Plugin/MapModule/Controller/MapeditorsController.php, app/Plugin/MapModule/Model/Mapeditor.php
[+]added getservicestatusbyhostuuid()
[+]improved popoverhoststatus
ITC-218 #dev-to-qa-queue
=> [+]added gethoststatusbyuuid()

app/Plugin/MapModule/Controller/MapeditorsController.php, app/Plugin/MapModule/Model/Mapeditor.php, app/Plugin/MapModule/View/Helper/MapstatusHelper.php, app/Plugin/MapModule/View/Mapeditors/popover_map_status.ctp, app/Plugin/MapModule/View/Mapeditors/view.ctp
[-]changed z-index of items in view mode
ITC-227
=> [-] fixed some mapstatus issues when a map is empty

app/Model/Service.php, app/webroot/js/app/components/StatusComponent.js
[+]added service description in servicesByHostContainerIds() method
=> [+]statusComponent for javascript added

app/Controller/DevicegroupsController.php, app/Controller/HostsController.php, app/Controller/LocationsController.php, app/Model/Devicegroup.php, app/Model/Host.php, app/Model/Location.php, app/Model/Service.php
[+]added redirection after delete failure in Devicegroups- and LocationsController
ITC-300
=> [+]added __allowDelete() in Devicegroup, Host, Location and Service

app/Plugin/MapModule/Controller/MapsController.php, app/Plugin/MapModule/Model/Map.php, app/Plugin/MapModule/View/Maps/add.ctp, app/Plugin/MapModule/View/Maps/edit.ctp
[+]Container in map add/edit is mandatory now ITC-329 #dev-to-qa-queue
=> [-]Tenant renamed to Container now in Map add/edit

app/Console/Command/Task/DebugConfigNagiosTask.php
[-]removed undefined $line var form if statement in while loop in tailf function
[-]removed ... from $this->..._buildUuidCache() in searchUuids function
=> [+]oitc debug --tail translates uuids to human readable names ITC-416

app/Plugin/MapModule/Controller/MapeditorsController.php, app/Plugin/MapModule/Model/Mapeditor.php, app/Plugin/MapModule/View/Mapeditors/popover_service_status.ctp
[-]also changed the host and servicestatusbyuuid and getServicestatusByHostUuid conditions to consider only active objects in mapeditor model
=> [-]fixed undefined offset from services popover in mapview ITC-651

app/View/Services/index.ctp
Added an addtional link for use in a plugin
=> Added an addtional link for use in a plugin

app/Controller/HostsController.php, app/webroot/smartadmin/css/your_style.css
[-]fixed dateformat for host datepicker
=> [-]fixed z-index for datepicker within modal dialogs ITC-644

app/UPDATE.sh
Added an adjustable php.ini for ITC-597
=> Adjustable php.ini for ITC-597

app/Config/acl_dependencies.php
ITC-431 Remove dashboard permissions from user group roles
=> ITC-431 Remove dashboard permissions from user group roles

app/Config/Environments.php, app/Plugin/MapModule/View/Helper/MapstatusHelper.php, app/Plugin/MapModule/View/Mapeditors/popover_host_status.ctp, app/Plugin/MapModule/View/Mapeditors/popover_hostgroup_status.ctp
=> [-]fixed summary state for host and hostgroups ITC-734 #dev-to-qa-queue

app/src/itnovum/openITCOCKPIT/InitialDatabase/Systemsetting.php
Resolve: System setting records get randomly overwritten on update
=> resolve issue ITC-919

.gitignore, app/Controller/Component/SudoResponseSocketComponent.php, app/Lib/SudoMessageInterface.php, app/Vendor/Ratchet/vendor/cboden/ratchet/src/Ratchet/Http/HttpRequestParser.php
Increase Maximum sudo_server header size to 8192 bytes.
=> ITC-1011 sudo_server 413 on Large Header (above 4096 bytes)

README.md
Updated system requirements: listed additional platforms
Minor textual improvements
Signed-off-by: Lenz Grimmer <lenz@grimmer.com>
=> Slightly improved README.md

app/Console/Command/GearmanWorkerShell.php, app/composer.json
Itc 961 Remove autocheck files
=> Itc 961 Remove autocheck files

app/Plugin/Admin/View/Layouts/default.ctp, app/View/Elements/Dashboard/host_piechart_180.ctp, app/View/Elements/Dashboard/host_piechart_360.ctp, app/View/Elements/Dashboard/service_piechart_180.ctp, app/View/Elements/Dashboard/service_piechart_360.ctp, app/webroot/js/app/controllers/hosts/browser_controller.js
If you click on hosts or services in the left main menu, the lists will be ordered by name
If you click on a status like up/down/warning/critical on the dashboard or the top menu
the host and service list will be ordered by State Since DESC
=> ITC-776 ITC-776a order host/service list by last_state_change desc

app/Config/Schema/schema_itcockpit_26.php, app/Console/Command/Task/NagiosExportTask.php, app/Console/Command/TestingShell.php, app/Controller/CalendarsController.php, app/Controller/TimeperiodsController.php, app/Model/Calendar.php, app/Model/Timeperiod.php, app/View/Timeperiods/add.ctp, app/View/Timeperiods/edit.ctp
=> Merge development into master

lib/Cake/Test/test_app/Plugin/TestPlugin/Controller/Component/TestPluginEmailComponent.php
=> [+]added missing test file ITC-1176

app/View/Elements/service_browser_menu.ctp
=> openITCOCKPIT 3.3.1

app/Config/acl_dependencies.php, app/Config/menu.php, app/View/Statusmaps/index.ctp
=> openITCOCKPIT 3.6.1-2

app/Config/acl_dependencies.php, app/Controller/AppController.php, app/Controller/CalendarsController.php, app/Controller/Component/TreeComponent.php, app/Controller/ContactgroupsController.php, app/Controller/HostgroupsController.php, app/Controller/HostsController.php, app/Controller/ServicegroupsController.php, app/Controller/ServicesController.php, app/Controller/ServicetemplategroupsController.php, app/Controller/TimeperiodsController.php, app/Model/Hostgroup.php, app/View/Hosts/disabled.ctp, app/View/Hosts/index.ctp, app/View/Hosts/not_monitored.ctp, app/src/itnovum/openITCOCKPIT/Core/ContainerNestedSet.php, app/src/itnovum/openITCOCKPIT/Filter/HostFilter.php, app/webroot/js/app/controllers/services/add_controller.js, app/webroot/js/scripts/controllers/ContainersIndexController.js, app/webroot/js/scripts/controllers/HostsDisabledController.js, app/webroot/js/scripts/controllers/HostsIndexController.js, app/webroot/js/scripts/controllers/HostsNotMonitoredController.js
- Improve performance of a system has lots of containers
=> Container performance

app/Controller/Component/LdapComponent.php, app/Vendor/adldap/adldap/src/Adldap.php, app/Vendor/adldap/adldap/src/Connections/Ldap.php
=> ITC-2178 #929

app/Locale/fr_FR/LC_MESSAGES/cake.po, app/Locale/fr_FR/LC_MESSAGES/cake_console.po, app/Locale/fr_FR/LC_MESSAGES/cake_dev.po, app/Locale/fr_FR/LC_MESSAGES/cake_pdf.po, app/Locale/fr_FR/LC_MESSAGES/cakepdf.po, app/Locale/fr_FR/LC_MESSAGES/clear_cache.po, app/Locale/fr_FR/LC_MESSAGES/debug_kit.po, app/Locale/fr_FR/LC_MESSAGES/default.po, app/Locale/fr_FR/LC_MESSAGES/oitc_console.po
This is the creation of the French translation.
- Based on the ORM branch;
- I've tried to follow the rules of #957 as much as possible.
=> Add French translation

app/Locale/de_DE/LC_MESSAGES/cake_console.po, app/Locale/de_DE/LC_MESSAGES/default.po
Begins addressing #957 for German. Will continue force-pushing until complete.
=> Add German translation

plugins/MapModule/src/Model/Table/MapsTable.php, src/itnovum/openITCOCKPIT/Monitoring/Naemon/ExternalCommands.php
=> openITCOCKPIT 4.0.4-1

bin/scripts/oitc3to4.sh, bin/scripts/oitcSat3to4.sh, config/Migrations/20201013093523_DisableAgentProxy.php, src/Controller/AgentconnectorController.php, src/Model/Entity/Agentconfig.php, src/Model/Table/AgentconfigsTable.php, src/Model/Table/AgentconnectorTable.php, src/Model/Table/HostsTable.php, src/Template/Agentconnector/config.php, src/Template/Agentconnector/pull_configurations.php, src/itnovum/openITCOCKPIT/Agent/AgentCertificateData.php, src/itnovum/openITCOCKPIT/Agent/HttpLoader.php, src/itnovum/openITCOCKPIT/Core/MonitoringEngine/NagiosConfigGenerator.php, webroot/js/scripts/controllers/Agentconnector/AgentconnectorsConfigController.js
=> openITCOCKPIT 4.1

SETUP.sh, UPDATE.sh, config/version.php, src/Identifier/LdapIdentifier.php
Create resource.cfg symlink if missing
=> Create resource.cfg symlink if missing

webroot/js/scripts/services/BBParserService.js
=> #ITC-2446 - URL is not correctly displayed as a link in Maps and Documentation

src/Template/Hostgroups/extended.php
=> fixing wrong service summary linking in hostgroup extended view ITC-2506

config/version.php, src/Command/GearmanWorkerCommand.php, src/config_templates/agent/agent.ini
This fix a minor bug in the SNMP Wizard which is not harmful but annoying for the user
=> openITCOCKPIT 4.2.1

package.json, src/Identifier/LdapIdentifier.php, src/Template/Systemsettings/index.php, src/itnovum/openITCOCKPIT/Ldap/LdapClient.php
This change is tested with npm 6.x and npm 7.x. It can be merged, even if we have to stay on npm 6 for now due to https://github.com/npm/cli/issues/2610
=> ITC-2594 npm 7.x for openITCOCKPIT Core

src/itnovum/openITCOCKPIT/Core/MonitoringEngine/NagiosConfigGenerator.php
Depends on https://github.com/it-novum/openITCOCKPIT/pull/1304
=> ITC-2701 Refactor handling of Checkmk configs and precompiled checks for Satellites

src/Middleware/AppAuthenticationMiddleware.php
https://github.com/cakephp/cakephp/commit/0defa45cbfa6cf222998d05a8dec40a7d936bdaf
=> Replace Zend framework packages with Laminas.

src/config_templates/graphing/grafana/grafana.ini
Update grafana.ini for Grafana 9.x to restore old user permissions. Disable Grafanas RBAC
=> openITCOCKPIT 4.5.0-2

src/Lib/AclDependencies.php
=> ITC-2873 Some wizards are only available for 'Administrator' user role

.gitignore, src/itnovum/openITCOCKPIT/Agent/AgentResponseToServices.php
=> ITC-2877 Set language for all Agent Checks to englisch

SETUP.sh, UPDATE.sh, bin/scripts/UPGRADE.sh, config/version.php
Enable Debug Mode when running UPDATE.sh or SETUP.sh
Tracked by ITC-2910
#1446 
[ITC-2910]: https://openitcockpit.atlassian.net/browse/ITC-2910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> #1446 ITC-2910 - Enable debug mode when running SETUP or UPDATE scripts

config/Migrations/20200129142142_Initial.php, config/Migrations/20200129144945_VersionFour.php, config/Migrations/20200211151417_Agentconnector.php, config/Migrations/20200515090906_UpdateAgentshostscache.php, config/Migrations/20200608122018_AddModuleToConfigurationQueue.php, config/Migrations/20200908122726_MysqlWizardMigration.php, config/Migrations/20200914091330_OAuth.php, config/Migrations/20201013093523_DisableAgentProxy.php, config/Migrations/20201214083457_AddPasswordToCustomMacros.php, config/Migrations/20210127115645_GolangAgent.php, config/Migrations/20210209130254_GolangAgentPush.php, config/Migrations/20210305074746_GolangPushAgentIndex.php, config/Migrations/20210511114343_ChangeMaxLimitForJson.php, config/Migrations/20210820121211_UpdateNotificationsEnabled.php, config/Migrations/20210915122539_MessageOfTheDay.php, config/Migrations/20211228081247_Ldapgroups.php, config/Migrations/20211229095033_LdapgroupsToUsergroups.php, config/Migrations/20220511053118_FilterBookmarks.php, config/Seeds/InstallSeed.php, plugins/GrafanaModule/config/Migrations/20200131081941_Initial.php, plugins/GrafanaModule/config/Migrations/20200427081944_Colors.php, plugins/GrafanaModule/config/Seeds/InstallSeed.php, plugins/MapModule/config/Migrations/20200131082324_Initial.php, plugins/MapModule/config/Migrations/20200228094239_RotationsTables.php, plugins/MapModule/config/Migrations/20200528134017_MapToSatellite.php, plugins/MapModule/config/Migrations/20210423061954_SaveMapeditorSettings.php, plugins/MapModule/config/Seeds/InstallSeed.php, plugins/MattermostModule/config/Migrations/20200123083021_CreateMattermostSettings.php, plugins/MattermostModule/config/Seeds/InstallSeed.php
Add return type to fix cakephp/migration PHP errors
=> openITCOCKPIT 4.5.5-1

config/version.php, src/Controller/HostsController.php, src/Lib/Traits/DatabasePartitionsTrait.php, webroot/js/scripts/directives/TemplateDiffDirective.js
https://bugs.mysql.com/bug.php?id=109685 🥹
=> openITCOCKPIT 4.6.1 to resolve bug within mysqldump

src/Template/Angular/host_browser_menu.php, src/Template/Angular/service_browser_menu.php, src/Template/Hosts/index.php, src/Template/Hosts/not_monitored.php, src/Template/Services/index.php, webroot/js/scripts/ng.app.js
ITC-2882
Service->Browser: Line break by copy button
=> ITC-2882 Service->Browser: Line break by copy button

src/itnovum/openITCOCKPIT/Core/Views/UserTime.php
=> Resolve #1410 by only passing timestamps

src/Template/Browsers/index.php, src/Template/Hosts/browser.php, src/Template/Hosts/index.php, src/Template/Services/index.php, src/Template/Services/service_list.php
* add sorting to the columns acknowledgement & downtime for different templates.
=> ITC-3026 Add sort option for "is acknowledged" and "is in downtime"

webroot/js/scripts/directives/HostStatusIconDirective.js, webroot/js/scripts/directives/ServiceStatusIconDirective.js
* Fix the default branch for both IconDirectives.
* Also force-null the hardState flag to remove (HARD) | (SOFT) extension.
* Remove testing changes.
=> ITC-3109 Wrong state in hosts & service status directive (not monitored view )

webroot/js/scripts/controllers/Administrator/AdministratorsDebugController.js
=> ITC-3102 OITC Service view graph switches to CPU Load after showing Systemhealth once

src/Command/NagiosNotificationCommand.php
Eventcorrelation Module: Option to treat services in downtime as Ok
=> ITC-3069 Eventcorrelation Module: Option to treat services in downtime as Ok

src/Template/Exports/index.php
- moved satellite status under export window
=> ITC-3124 Move Satellite Status Overview in Configuration Refresh to the bottom

src/Template/Agentconnector/create_services.php, src/itnovum/openITCOCKPIT/Agent/AgentResponseToServices.php, src/itnovum/openITCOCKPIT/InitialDatabase/Agent.php, src/itnovum/openITCOCKPIT/Perfdata/UnitScaler.php
Add support to monitor Free Disk Space and System Uptime via the openITCOCKPIT Monitoring Agent
=> ITC-2905 openITCOCKPIT Monitoring Agent: Disk usage - check free space instead of used space when using unit GB

src/Controller/CalendarsController.php, src/Model/Entity/Calendar.php, src/Model/Table/ContainersTable.php
* Add condition when storing a calendar: If timeranges exist and the new container is not part of the current container's path, show a notice.
=> ITC-3105 Time periods: Moving a calendar to a different container won't delete it from time periods

config/Migrations/20240115103618_AddLastLoginToUsersAndLastUseToApiKeys.php, src/Controller/ProfileController.php, src/Controller/UsersController.php, src/Model/Entity/Apikey.php, webroot/js/scripts/controllers/ProfileEditController.js
- fixed bug, which does not allow to update the user
- fixed bug, which overwrites api changes after user update
=> ITC-2758 Add column "last login" to users overview

src/Model/Table/HostsTable.php
This branch is probably a duplicate of ITC-3142 #1624
=> ITC-3145 Checkmk Module: Implement Re-Discovery

src/Controller/ServicegroupsController.php, src/itnovum/openITCOCKPIT/Filter/ServicetemplateFilter.php, webroot/js/scripts/controllers/Servicegroups/ServicegroupsAddController.js, webroot/js/scripts/controllers/Servicegroups/ServicegroupsEditController.js
- fixed bug, which does not return prometheus service templates as search results
=> ITC-3160 Prometheus Module: Service Group Edit filters Prometheus Service Templates

src/itnovum/openITCOCKPIT/Monitoring/DefaultMacros.php
https://github.com/naemon/naemon.github.io/commit/51ff6c2899a783c99d90413bd41178c39653a2cb
=> ITC-3161 Update list of standard Macros in Naemon

webroot/js/scripts/directives/MassActivateDirective.js, webroot/js/scripts/directives/MassDeactivateDirective.js, webroot/js/scripts/directives/MassDeleteDirective.js
- fixed bug, which does not reset counter after mass action
=> ITC-1680 Selected objects counter of mass delete function is not reset after deletion

.gitignore, src/Template/email/html/notification_host.php, src/Template/email/html/notification_service.php, webroot/js/scripts/controllers/Hosts/HostsBrowserController.js, webroot/js/scripts/controllers/Services/ServicesBrowserController.js
* Adds Notifications to Microsoft Teams via WebHook.
* Notifications are coloured regarding the status and show output.
* Also they show links to the hosts and service mentioned in the notification.
* If you send a problem (CRITICAL or WARNING or UNKNOWN), the notifications contain a [acknowledge] button.
=> ITC-2626: Notifications: Microsoft Teams

plugins/MapModule/src/Controller/MapeditorsController.php
* Only fetch Service Performance Data for 'service' type requests
=> ITC-3153 New Performance Data Standard & Adapters for Nagios and Prometheus

src/itnovum/openITCOCKPIT/Core/Menu/Menu.php
=> ITC-3217: Core Hostgroups

src/itnovum/openITCOCKPIT/Core/Menu/Menu.php
=>  ITC-3241: Core: Servicegroups

src/Controller/ServicetemplategroupsController.php
This  will fix the service template groups permission check for non root users and resolve #1695
=> ITC-3355 Fix permission check for service template groups

src/itnovum/openITCOCKPIT/Core/Menu/Menu.php
=> ITC-3338: Core: SystemHealthUsers

src/Controller/UsersController.php, src/itnovum/openITCOCKPIT/Core/Menu/Menu.php
* Add Menu
* Add server time and server timezone to API
=> ITC-3210: Core: Users

src/itnovum/openITCOCKPIT/Core/Menu/Menu.php
=> ITC-3224: Downtime Reports

src/Controller/TenantsController.php
* Pass hasRootPrivileges to front-end to hide the [add] button on demand.
=> ITC-3426-Jan

src/Controller/HostgroupsController.php, src/Controller/HostsController.php, src/Controller/ServicegroupsController.php, src/Controller/ServicesController.php
* Added column %name%_readable right behind the original timestamp export columns where missing
=> ITC-3447 - Export Timestamp in CSV with readable formats

config/Migrations/20250526075038_UserDepartment.php, src/Controller/ServicesController.php, src/Controller/UsersController.php, src/Model/Entity/User.php, src/Model/Table/UsersTable.php, src/itnovum/openITCOCKPIT/Ldap/LdapClient.php
* Add new optional field "Department" to users.
* Import the fields "Company" and "Department" from LDAP.
* On LDAP Users, make the fields "Company" and "Department" readonly.
=> ITC-3464 - User Configuration -  Add field <department>

src/Controller/UsersController.php, src/Model/Table/UsersTable.php
* Force user to reset password when oAuth is enabled.
=>  ITC-3467 Make "is oAuth user" editable

plugins/MapModule/src/Controller/BackgroundUploadsController.php
Thanks to @kbilev for reporting this
=> ITC-3522 Fix to save the user_id for map image uploads

.gitignore, config/Migrations/20250527090453_StatuspagePublicHeader.php, config/version.php, plugins/MapModule/src/Controller/BackgroundUploadsController.php, src/Controller/AppController.php, src/Controller/HostsController.php, src/Controller/ServicesController.php, src/Controller/UsersController.php, src/Model/Entity/Statuspage.php, src/Model/Table/StatuspagesTable.php, src/Model/Table/UsersTable.php, src/Template/Statuspages/public_view.php, src/Template/layout/statuspage_public.php, src/itnovum/openITCOCKPIT/ConfigGenerator/PhpFpmOitc.php, src/itnovum/openITCOCKPIT/Core/Views/Logo.php, webroot/css/statuspage.css
* Add same logo upload as for statuspage dynamic header feature
=> ITC-3483 - Extend DesignModule
